import Foundation

struct RagaDatabase {
    static let allRagas: [Raga] = [
        Raga(id: "yaman", name: "Yaman", alternateNames: ["Kalyan"], thaat: "Kalyan",
             aroh: [.sa, .re, .ga, .maTivra, .pa, .dha, .ni],
             avroh: [.ni, .dha, .pa, .maTivra, .ga, .re, .sa],
             vadi: .ga, samvadi: .ni, timeOfDay: "Evening",
             description: "One of the most fundamental ragas in Hindustani music. Evokes a mood of devotion and serenity, typically performed in the first part of the night."),

        Raga(id: "bhairav", name: "Bhairav", alternateNames: [], thaat: "Bhairav",
             aroh: [.sa, .reKomal, .ga, .ma, .pa, .dhaKomal, .ni],
             avroh: [.ni, .dhaKomal, .pa, .ma, .ga, .reKomal, .sa],
             vadi: .dha, samvadi: .re, timeOfDay: "Morning",
             description: "A majestic morning raga associated with Lord Shiva. Creates a solemn and devotional atmosphere."),

        Raga(id: "bhairavi", name: "Bhairavi", alternateNames: ["Sindhu Bhairavi"], thaat: "Bhairavi",
             aroh: [.sa, .reKomal, .gaKomal, .ma, .pa, .dhaKomal, .niKomal],
             avroh: [.niKomal, .dhaKomal, .pa, .ma, .gaKomal, .reKomal, .sa],
             vadi: .ma, samvadi: .sa, timeOfDay: "Morning",
             description: "Often called the queen of ragas. Uses all komal swaras and expresses deep devotion and pathos. Typically the concluding raga in a concert."),

        Raga(id: "bilawal", name: "Bilawal", alternateNames: ["Alhaiya Bilawal"], thaat: "Bilawal",
             aroh: [.sa, .re, .ga, .pa, .dha, .ni],
             avroh: [.ni, .dha, .pa, .ma, .ga, .re, .sa],
             vadi: .dha, samvadi: .ga, timeOfDay: "Morning",
             description: "A cheerful morning raga equivalent to the Western major scale. Creates a bright and happy mood."),

        Raga(id: "khamaj", name: "Khamaj", alternateNames: [], thaat: "Khamaj",
             aroh: [.sa, .ga, .ma, .pa, .dha, .ni],
             avroh: [.ni, .dha, .pa, .ma, .ga, .re, .sa],
             vadi: .ga, samvadi: .ni, timeOfDay: "Night",
             description: "A romantic evening raga commonly used in light classical forms like thumri and dadra."),

        Raga(id: "kafi", name: "Kafi", alternateNames: [], thaat: "Kafi",
             aroh: [.sa, .re, .gaKomal, .ma, .pa, .dha, .niKomal],
             avroh: [.niKomal, .dha, .pa, .ma, .gaKomal, .re, .sa],
             vadi: .pa, samvadi: .sa, timeOfDay: "Night",
             description: "A spring raga associated with the festival of Holi. Evokes romance and playfulness."),

        Raga(id: "asavari", name: "Asavari", alternateNames: [], thaat: "Asavari",
             aroh: [.sa, .re, .ma, .pa, .dhaKomal],
             avroh: [.dhaKomal, .pa, .ma, .gaKomal, .re, .sa],
             vadi: .dha, samvadi: .ga, timeOfDay: "Late morning",
             description: "A contemplative raga with a serious, pensive mood. Often associated with the feeling of renunciation."),

        Raga(id: "todi", name: "Todi", alternateNames: ["Miyan ki Todi"], thaat: "Todi",
             aroh: [.sa, .reKomal, .gaKomal, .maTivra, .pa, .dhaKomal, .ni],
             avroh: [.ni, .dhaKomal, .pa, .maTivra, .gaKomal, .reKomal, .sa],
             vadi: .dha, samvadi: .ga, timeOfDay: "Morning",
             description: "A profound morning raga with an intense, deeply emotional character. Uses three komal notes with tivra Ma."),

        Raga(id: "marwa", name: "Marwa", alternateNames: [], thaat: "Marwa",
             aroh: [.sa, .reKomal, .ga, .maTivra, .dha, .ni],
             avroh: [.ni, .dha, .maTivra, .ga, .reKomal, .sa],
             vadi: .re, samvadi: .dha, timeOfDay: "Evening",
             description: "A serious sunset raga that omits Pa. Creates an atmosphere of restless longing and anticipation."),

        Raga(id: "purvi", name: "Purvi", alternateNames: [], thaat: "Purvi",
             aroh: [.sa, .reKomal, .ga, .maTivra, .pa, .dhaKomal, .ni],
             avroh: [.ni, .dhaKomal, .pa, .maTivra, .ga, .reKomal, .sa],
             vadi: .ga, samvadi: .ni, timeOfDay: "Evening",
             description: "A contemplative evening raga expressing a mood of quiet devotion and spiritual yearning."),

        Raga(id: "bageshri", name: "Bageshri", alternateNames: ["Bageshree"], thaat: "Kafi",
             aroh: [.sa, .gaKomal, .ma, .dha, .niKomal],
             avroh: [.niKomal, .dha, .pa, .ma, .gaKomal, .re, .sa],
             vadi: .ma, samvadi: .sa, timeOfDay: "Night",
             description: "A romantic night raga with a tender, emotional quality. Popular in both classical and semi-classical forms."),

        Raga(id: "darbari_kanada", name: "Darbari Kanada", alternateNames: ["Darbari"], thaat: "Asavari",
             aroh: [.sa, .re, .gaKomal, .ma, .pa, .dhaKomal, .niKomal],
             avroh: [.niKomal, .dhaKomal, .pa, .ma, .gaKomal, .re, .sa],
             vadi: .re, samvadi: .pa, timeOfDay: "Late night",
             description: "A majestic and grand raga associated with the Mughal court. The distinctive andolan on Ga komal gives it a regal character."),

        Raga(id: "malkauns", name: "Malkauns", alternateNames: ["Malkosh"], thaat: "Bhairavi",
             aroh: [.sa, .gaKomal, .ma, .dhaKomal, .niKomal],
             avroh: [.niKomal, .dhaKomal, .ma, .gaKomal, .sa],
             vadi: .ma, samvadi: .sa, timeOfDay: "Late night",
             description: "A powerful pentatonic raga creating a meditative and mysterious atmosphere. Uses only komal swaras."),

        Raga(id: "durga", name: "Durga", alternateNames: [], thaat: "Bilawal",
             aroh: [.sa, .re, .ma, .pa, .dha],
             avroh: [.dha, .pa, .ma, .re, .sa],
             vadi: .ma, samvadi: .sa, timeOfDay: "Night",
             description: "A beautiful pentatonic raga with a devotional and serene quality. Omits Ga and Ni."),

        Raga(id: "hansadhwani", name: "Hansadhwani", alternateNames: ["Hamsadhwani"], thaat: "Bilawal",
             aroh: [.sa, .re, .ga, .pa, .ni],
             avroh: [.ni, .pa, .ga, .re, .sa],
             vadi: .ga, samvadi: .ni, timeOfDay: "Night",
             description: "A joyous pentatonic raga of South Indian origin. Light and auspicious, often used to begin concerts."),

        Raga(id: "desh", name: "Desh", alternateNames: [], thaat: "Khamaj",
             aroh: [.sa, .re, .ma, .pa, .ni],
             avroh: [.ni, .dha, .pa, .ma, .ga, .re, .sa],
             vadi: .re, samvadi: .pa, timeOfDay: "Night",
             description: "A rain-season raga that evokes patriotic and romantic feelings. Light and melodious."),

        Raga(id: "tilak_kamod", name: "Tilak Kamod", alternateNames: [], thaat: "Khamaj",
             aroh: [.sa, .re, .ga, .pa, .dha],
             avroh: [.dha, .pa, .ga, .re, .sa],
             vadi: .ga, samvadi: .dha, timeOfDay: "Night",
             description: "A sweet and romantic night raga with a gentle, flowing character."),

        Raga(id: "bihag", name: "Bihag", alternateNames: [], thaat: "Bilawal",
             aroh: [.sa, .ga, .maTivra, .pa, .ni],
             avroh: [.ni, .dha, .pa, .maTivra, .ga, .re, .sa],
             vadi: .ga, samvadi: .ni, timeOfDay: "Night",
             description: "A captivating raga that combines the beauty of Bilawal and Kalyan. Romantic and deeply melodious."),

        Raga(id: "kedar", name: "Kedar", alternateNames: [], thaat: "Kalyan",
             aroh: [.sa, .ma, .maTivra, .pa, .dha],
             avroh: [.dha, .pa, .maTivra, .ma, .ga, .re, .sa],
             vadi: .ma, samvadi: .sa, timeOfDay: "Night",
             description: "A devotional raga associated with Lord Shiva. Has a distinctive use of both Ma and Tivra Ma."),

        Raga(id: "shankara", name: "Shankara", alternateNames: [], thaat: "Bilawal",
             aroh: [.sa, .re, .ga, .pa, .ni],
             avroh: [.ni, .pa, .ga, .re, .sa],
             vadi: .ga, samvadi: .ni, timeOfDay: "Night",
             description: "A pentatonic raga of peaceful and devotional nature. Similar to Hansadhwani but in Bilawal framework."),

        Raga(id: "jaunpuri", name: "Jaunpuri", alternateNames: [], thaat: "Asavari",
             aroh: [.sa, .re, .gaKomal, .ma, .pa, .dhaKomal, .ni],
             avroh: [.ni, .dhaKomal, .pa, .ma, .gaKomal, .re, .sa],
             vadi: .re, samvadi: .dha, timeOfDay: "Late morning",
             description: "A beautiful raga named after the city of Jaunpur. Serious yet approachable."),

        Raga(id: "multani", name: "Multani", alternateNames: [], thaat: "Todi",
             aroh: [.sa, .gaKomal, .maTivra, .pa, .niKomal],
             avroh: [.niKomal, .dhaKomal, .pa, .maTivra, .gaKomal, .re, .sa],
             vadi: .pa, samvadi: .sa, timeOfDay: "Afternoon",
             description: "An afternoon raga of intense and yearning character. Uses the Todi framework but with distinct treatment."),

        Raga(id: "lalit", name: "Lalit", alternateNames: [], thaat: "Marwa",
             aroh: [.sa, .reKomal, .ga, .maTivra, .ma, .dha, .ni],
             avroh: [.ni, .dha, .ma, .maTivra, .ga, .reKomal, .sa],
             vadi: .ma, samvadi: .sa, timeOfDay: "Dawn",
             description: "A sublime dawn raga that uses both Ma and Tivra Ma but omits Pa. Creates an extraordinary mystical atmosphere."),

        Raga(id: "sohni", name: "Sohni", alternateNames: [], thaat: "Marwa",
             aroh: [.sa, .reKomal, .ga, .maTivra, .dha, .ni],
             avroh: [.ni, .dha, .pa, .maTivra, .ga, .reKomal, .sa],
             vadi: .dha, samvadi: .ga, timeOfDay: "Night",
             description: "A light and romantic night raga related to Marwa. Tender and graceful."),

        Raga(id: "shree", name: "Shree", alternateNames: ["Sri"], thaat: "Purvi",
             aroh: [.sa, .re, .maTivra, .pa, .dhaKomal, .ni],
             avroh: [.ni, .dhaKomal, .pa, .maTivra, .ga, .re, .sa],
             vadi: .re, samvadi: .pa, timeOfDay: "Evening",
             description: "A majestic and auspicious raga associated with prosperity and grandeur."),

        Raga(id: "basant", name: "Basant", alternateNames: [], thaat: "Purvi",
             aroh: [.sa, .ga, .maTivra, .pa, .dhaKomal, .ni],
             avroh: [.ni, .dhaKomal, .pa, .maTivra, .ga, .sa],
             vadi: .dha, samvadi: .re, timeOfDay: "Night",
             description: "A joyous raga associated with the spring season. Brilliant and celebratory."),

        Raga(id: "miyan_ki_malhar", name: "Miyan ki Malhar", alternateNames: ["Mian Malhar"], thaat: "Kafi",
             aroh: [.sa, .re, .ma, .pa, .niKomal, .dha, .ni],
             avroh: [.ni, .dha, .pa, .ma, .gaKomal, .re, .sa],
             vadi: .ma, samvadi: .sa, timeOfDay: "Rainy season",
             description: "One of the most beloved Malhar ragas, associated with monsoon rains. Attributed to Tansen."),

        Raga(id: "megh", name: "Megh", alternateNames: ["Megh Malhar"], thaat: "Kafi",
             aroh: [.sa, .re, .ma, .pa, .niKomal],
             avroh: [.niKomal, .dha, .pa, .ma, .re, .sa],
             vadi: .ma, samvadi: .sa, timeOfDay: "Rainy season",
             description: "A rain raga evoking the imagery of gathering monsoon clouds. Majestic and powerful."),

        Raga(id: "brindavani_sarang", name: "Brindavani Sarang", alternateNames: [], thaat: "Kafi",
             aroh: [.sa, .re, .ma, .pa, .ni],
             avroh: [.ni, .dha, .pa, .ma, .re, .sa],
             vadi: .re, samvadi: .pa, timeOfDay: "Afternoon",
             description: "A sweet afternoon raga associated with the pastoral land of Brindavan. Light and pleasant."),

        Raga(id: "ahir_bhairav", name: "Ahir Bhairav", alternateNames: [], thaat: "Bhairav",
             aroh: [.sa, .reKomal, .ga, .ma, .pa, .dha, .niKomal],
             avroh: [.niKomal, .dha, .pa, .ma, .ga, .reKomal, .sa],
             vadi: .ma, samvadi: .sa, timeOfDay: "Morning",
             description: "A soothing morning raga combining elements of Ahir and Bhairav. Gentle and devotional."),

        Raga(id: "charukeshi", name: "Charukeshi", alternateNames: [], thaat: "Khamaj",
             aroh: [.sa, .re, .ga, .ma, .pa, .dhaKomal, .niKomal],
             avroh: [.niKomal, .dhaKomal, .pa, .ma, .ga, .re, .sa],
             vadi: .pa, samvadi: .sa, timeOfDay: "Night",
             description: "A raga of South Indian origin that has gained popularity in Hindustani music. Evokes a reflective mood."),

        Raga(id: "kirwani", name: "Kirwani", alternateNames: ["Kirvani"], thaat: "Kafi",
             aroh: [.sa, .re, .gaKomal, .ma, .pa, .dhaKomal, .ni],
             avroh: [.ni, .dhaKomal, .pa, .ma, .gaKomal, .re, .sa],
             vadi: .ma, samvadi: .sa, timeOfDay: "Night",
             description: "A dramatic night raga with a unique combination of komal Ga, komal Dha, and shuddha Ni. Intense and passionate."),

        Raga(id: "jayjaywanti", name: "Jayjaywanti", alternateNames: ["Jaijaiwanti", "Dwijavanti"], thaat: "Khamaj",
             aroh: [.sa, .re, .ga, .ma, .pa, .dha, .ni],
             avroh: [.ni, .dha, .pa, .ma, .gaKomal, .re, .sa],
             vadi: .re, samvadi: .pa, timeOfDay: "Night",
             description: "A versatile raga that uses both shuddha and komal Ga. Creates a mood of joy and celebration."),

        Raga(id: "pahadi", name: "Pahadi", alternateNames: [], thaat: "Bilawal",
             aroh: [.sa, .re, .ga, .pa, .dha],
             avroh: [.dha, .pa, .ga, .re, .sa],
             vadi: .ga, samvadi: .dha, timeOfDay: "Night",
             description: "A folk-based raga evoking the beauty of mountain landscapes. Simple and melodious."),

        Raga(id: "pilu", name: "Pilu", alternateNames: [], thaat: "Kafi",
             aroh: [.sa, .re, .gaKomal, .ma, .pa, .dha, .niKomal],
             avroh: [.niKomal, .dha, .pa, .ma, .gaKomal, .re, .sa],
             vadi: .ga, samvadi: .ni, timeOfDay: "Night",
             description: "A popular light raga used extensively in thumri, ghazal, and film music. Romantic and expressive."),

        Raga(id: "jhinjhoti", name: "Jhinjhoti", alternateNames: [], thaat: "Khamaj",
             aroh: [.sa, .re, .ga, .pa, .dha, .ni],
             avroh: [.ni, .dha, .pa, .ma, .ga, .re, .sa],
             vadi: .dha, samvadi: .ga, timeOfDay: "Night",
             description: "A sweet and light raga commonly heard in thumri and film music. Evokes romantic sentiments."),

        Raga(id: "tilang", name: "Tilang", alternateNames: [], thaat: "Khamaj",
             aroh: [.sa, .ga, .ma, .pa, .ni],
             avroh: [.ni, .dha, .pa, .ma, .ga, .sa],
             vadi: .ga, samvadi: .ni, timeOfDay: "Night",
             description: "A light and romantic pentatonic-hexatonic raga. Sweet and melodious."),

        Raga(id: "bhimpalasi", name: "Bhimpalasi", alternateNames: [], thaat: "Kafi",
             aroh: [.sa, .re, .gaKomal, .ma, .pa, .dha, .niKomal],
             avroh: [.niKomal, .dha, .pa, .ma, .gaKomal, .re, .sa],
             vadi: .ma, samvadi: .sa, timeOfDay: "Afternoon",
             description: "A beloved afternoon raga with a yearning, romantic quality. One of the most popular ragas for beginners."),

        Raga(id: "madhuvanti", name: "Madhuvanti", alternateNames: [], thaat: "Todi",
             aroh: [.sa, .gaKomal, .maTivra, .pa, .ni],
             avroh: [.ni, .dhaKomal, .pa, .maTivra, .gaKomal, .re, .sa],
             vadi: .maTivra, samvadi: .sa, timeOfDay: "Afternoon",
             description: "A sweet afternoon raga with a distinctive ascending phrase. Romantic and evocative."),

        Raga(id: "patdeep", name: "Patdeep", alternateNames: ["Pat Deep"], thaat: "Kafi",
             aroh: [.sa, .gaKomal, .ma, .pa, .niKomal],
             avroh: [.niKomal, .dha, .pa, .ma, .gaKomal, .re, .sa],
             vadi: .pa, samvadi: .sa, timeOfDay: "Afternoon",
             description: "A serene afternoon raga with a contemplative quality. Gentle and introspective."),

        Raga(id: "puriya", name: "Puriya", alternateNames: [], thaat: "Marwa",
             aroh: [.sa, .reKomal, .ga, .maTivra, .dha, .ni],
             avroh: [.ni, .dha, .maTivra, .ga, .reKomal, .sa],
             vadi: .ga, samvadi: .ni, timeOfDay: "Evening",
             description: "A grand evening raga that avoids Pa. Deep, serious, and meditative."),

        Raga(id: "puriya_dhanashri", name: "Puriya Dhanashri", alternateNames: [], thaat: "Purvi",
             aroh: [.sa, .reKomal, .ga, .maTivra, .pa, .dhaKomal, .ni],
             avroh: [.ni, .dhaKomal, .pa, .maTivra, .ga, .reKomal, .sa],
             vadi: .pa, samvadi: .sa, timeOfDay: "Evening",
             description: "An evening raga combining qualities of Puriya and Dhanashri. Profound and expressive."),

        Raga(id: "kamod", name: "Kamod", alternateNames: [], thaat: "Kalyan",
             aroh: [.sa, .re, .pa, .dha, .ni],
             avroh: [.ni, .dha, .pa, .maTivra, .ga, .re, .sa],
             vadi: .pa, samvadi: .sa, timeOfDay: "Night",
             description: "A sweet and romantic night raga. Light and joyful with a playful character."),

        Raga(id: "nand", name: "Nand", alternateNames: ["Anandi"], thaat: "Kalyan",
             aroh: [.sa, .re, .ga, .ma, .pa, .dha, .ni],
             avroh: [.ni, .dha, .pa, .maTivra, .ga, .re, .sa],
             vadi: .sa, samvadi: .pa, timeOfDay: "Night",
             description: "A mixed raga using both Ma and Tivra Ma. Joyous and celebratory."),

        Raga(id: "hameer", name: "Hameer", alternateNames: [], thaat: "Kalyan",
             aroh: [.sa, .re, .ga, .ma, .pa, .dha, .ni],
             avroh: [.ni, .dha, .pa, .maTivra, .ga, .ma, .re, .sa],
             vadi: .dha, samvadi: .ga, timeOfDay: "Night",
             description: "A grand and majestic night raga with bold phrases. Uses both Ma and Tivra Ma."),

        Raga(id: "gorakh_kalyan", name: "Gorakh Kalyan", alternateNames: [], thaat: "Khamaj",
             aroh: [.sa, .re, .ma, .pa, .dha],
             avroh: [.dha, .pa, .ma, .ga, .re, .sa],
             vadi: .pa, samvadi: .sa, timeOfDay: "Night",
             description: "A pentatonic night raga with a serene quality. Simple yet deeply moving."),

        Raga(id: "maru_bihag", name: "Maru Bihag", alternateNames: [], thaat: "Kalyan",
             aroh: [.sa, .ga, .maTivra, .pa, .ni],
             avroh: [.ni, .dha, .pa, .maTivra, .ga, .re, .sa],
             vadi: .ga, samvadi: .ni, timeOfDay: "Night",
             description: "A romantic night raga combining elements of Marwa and Bihag. Captivating and serene."),

        Raga(id: "des", name: "Des", alternateNames: [], thaat: "Khamaj",
             aroh: [.sa, .re, .ma, .pa, .ni],
             avroh: [.ni, .dha, .pa, .ma, .ga, .re, .sa],
             vadi: .re, samvadi: .pa, timeOfDay: "Night",
             description: "A beloved raga associated with patriotic and romantic sentiments. Light and tuneful."),
    ]
}
